### ISSUE TITLE
Traceback: "PyBitTorrent.Exceptions.UnknownTracker: wss://tracker.openwebtorrent.com:443/announce"

### ISSUE THREAD

**Issue by sanderjo** [gaffner/PyBitTorrent#29]
I get a Traceback on a certain .torrent: 

`PyBitTorrent.Exceptions.UnknownTracker: wss://tracker.openwebtorrent.com:443/announce`

"wss" seems a valid protocol: websocket. And there is python client for it: https://pypi.org/project/websocket-client/

If PyBitTorrent does it not support it (fair enough), a Traceback is a pity. Maybe just ignoring/skipping the wss could be a workaround?

For reference: Torrent is here (open source Armbian image): https://xogium.performanceservers.nl/archive/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz.torrent

```
sander@zwarte:~/git/PyBitTorrent$ ~/pybittorrent-venv/bin/python3 examples/Client.py --torrent ~/Downloads/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz.torrent --output-directory ~
2024-11-30 19:37:26.400 INFO TorrentFile - __init__: Start reading from BitTorrent file
{
    'announce': 'udp://open.demonii.com:1337/announce',
    'announce-list': [
        ['udp://open.demonii.com:1337/announce'],
        ['http://t.nyaatracker.com:80/announce'],
        ['http://1337.abcvg.info:80/announce'],
        ['udp://thetracker.org:80/announce'],
        ['udp://serpb.vpsburti.com:6969/announce'],
        ['http://nyaa.tracker.wf:7777/announce'],
        ['https://tracker.tamersunion.org:443/announce'],
        ['udp://ns-1.x-fins.com:6969/announce'],
        ['http://tracker.moxing.party:6969/announce'],
        ['udp://open.free-tracker.ga:6969/announce'],
        ['udp://open.stealth.si:80/announce'],
        ['udp://opentor.org:2710/announce'],
        ['udp://bandito.byterunner.io:6969/announce'],
        ['http://www.wareztorrent.com:80/announce'],
        ['https://tracker.gcrenwp.top:443/announce'],
        ['http://tracker810.xyz:11450/announce'],
        ['http://tk.leechshield.link:80/announce'],
        ['udp://run.publictracker.xyz:6969/announce'],
        ['udp://ns1.monolithindustries.com:6969/announce'],
        ['http://tracker.corpscorp.online:80/announce'],
        ['https://tracker.leechshield.link:443/announce'],
        ['udp://evan.im:6969/announce'],
        ['wss://tracker.openwebtorrent.com:443/announce'],
        ['udp://tracker.skyts.net:6969/announce'],
        ['http://tracker-zhuqiy.dgj055.icu:80/announce'],
        ['https://tracker1.520.jp:443/announce'],
        ['http://tracker.bz:80/announce'],
        ['https://trackers.mlsub.net:443/announce'],
        ['udp://tracker.opentrackr.org:1337/announce'],
        ['udp://ec2-18-191-163-220.us-east-2.compute.amazonaws.com:6969/announce'],
        ['udp://martin-gebhardt.eu:25/announce'],
        ['udp://tracker.gigantino.net:6969/announce'],
        ['http://bt.okmp3.ru:2710/announce'],
        ['http://tracker2.itzmx.com:6961/announce'],
        ['https://tracker.kuroy.me:443/announce'],
        ['udp://trackarr.org:6969/announce'],
        ['udp://ttk2.nbaonlineservice.com:6969/announce'],
        ['udp://bt.rer.lol:6969/announce'],
        ['udp://z.mercax.com:53/announce'],
        ['udp://tracker.dump.cl:6969/announce'],
        ['http://tracker.beeimg.com:6969/announce'],
        ['http://torrentsmd.com:8080/announce'],
        ['https://1337.abcvg.info:443/announce'],
        ['https://tr.burnabyhighstar.com:443/announce'],
        ['udp://tracker.srv00.com:6969/announce'],
        ['http://tracker.xiaoduola.xyz:6969/announce'],
        ['udp://tracker.gmi.gd:6969/announce'],
        ['udp://exodus.desync.com:6969/announce'],
        ['udp://u4.trakx.crim.ist:1337/announce'],
        ['http://tracker.tfile.co:80/announce'],
        ['udp://open.tracker.cl:1337/announce'],
        ['http://tracker.lintk.me:2710/announce'],
        ['https://tr.abir.ga:443/announce'],
        ['http://tracker4.itzmx.com:2710/announce'],
        ['udp://tracker.breizh.pm:6969/announce'],
        ['http://tr.kxmp.cf:80/announce'],
        ['udp://tracker.fnix.net:6969/announce'],
        ['udp://tracker.doko.moe:6969/announce'],
        ['https://tracker.yemekyedim.com:443/announce'],
        ['udp://tracker.dler.com:6969/announce'],
        ['http://public.tracker.vraphim.com:6969/announce'],
        ['udp://tracker.deadorbit.nl:6969/announce'],
        ['http://tracker3.itzmx.com:6961/announce'],
        ['udp://odd-hd.fr:6969/announce'],
        ['udp://tracker.0x7c0.com:6969/announce'],
        ['http://tracker.vraphim.com:6969/announce'],
        ['udp://tracker.torrent.eu.org:451/announce'],
        ['http://www.all4nothin.net:80/announce.php'],
        ['http://tracker.ipv6tracker.org:80/announce'],
        ['udp://u6.trakx.crim.ist:1337/announce'],
        ['http://tracker.bt4g.com:2095/announce'],
        ['udp://seedpeer.net:6969/announce'],
        ['udp://open.tracker.ink:6969/announce'],
        ['udp://amigacity.xyz:6969/announce'],
        ['https://tracker.moeking.me:443/announce'],
        ['http://tk.greedland.net:80/announce']
    ],
    'comment': 'Armbian torrent for Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
    'created by': 'mktorrent 1.1',
    'creation date': 1731858149,
    'info': {'length': 419510976, 'name': 'Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz', 'piece length': 262144, 'pieces': ''},
    'url-list': [
        'http://in.mirrors.naho.moe/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirrors.shanghaitech.edu.cn/armbian-releases/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://fi.mirror.armbian.de/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirror-eu-de1.armbian.airframes.io/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://wa.mirrors.naho.moe/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirrors.bfsu.edu.cn/armbian-releases/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirror-us-stl1.armbian.airframes.io/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirror-us-sea2.armbian.airframes.io/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirrors.aliyun.com/armbian-releases/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://uk.mirrors.naho.moe/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://armbian.nardol.ovh/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://sg.mirrors.naho.moe/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://repo.jing.rocks/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://kr.mirrors.naho.moe/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirrors.ustc.edu.cn/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://de.mirrors.naho.moe/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://sg.sbcmirror.org/armbian/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirrors.tuna.tsinghua.edu.cn/armbian-releases/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://es.sbcmirror.org/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://armbian.hosthatch.com/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirror.yandex.ru/mirrors/armbian/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirror-us-phx1.armbian.airframes.io/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://armbian.atomonetworks.com/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://xogium.performanceservers.nl/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirror.iscas.ac.cn/armbian-releases/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://stpete-mirror.armbian.com/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirrors.nju.edu.cn/armbian-releases/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://au.mirrors.naho.moe/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirror.twds.com.tw/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirror-us-sea1.armbian.airframes.io/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://jp.mirrors.naho.moe/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://au.sbcmirror.org/armbian/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirror.vinehost.net/armbian/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://armbian.chi.auroradev.org/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://fastmirror.pp.ua/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://k-space.ee.armbian.com/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirrors.jevincanders.net/armbian/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://armbian.lv.auroradev.org/dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        '\nhttp://mirrors.dotsrc.org/armbian-dl/bananapif3/archive/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz',
        ''
    ]
}
Traceback (most recent call last):
  File "/home/sander/git/PyBitTorrent/examples/Client.py", line 29, in <module>
    main()
  File "/home/sander/git/PyBitTorrent/examples/Client.py", line 20, in main
    torrent_client = TorrentClient(torrent=args.torrent, max_peers=args.max_peers,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sander/pybittorrent-venv/lib/python3.12/site-packages/PyBitTorrent/Bittorrent.py", line 79, in __init__
    new_trackers = TrackerFactory.create_trackers(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sander/pybittorrent-venv/lib/python3.12/site-packages/PyBitTorrent/TrackerFactory.py", line 35, in create_trackers
    tracker = TrackerFactory.create_tracker(url[0])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sander/pybittorrent-venv/lib/python3.12/site-packages/PyBitTorrent/TrackerFactory.py", line 25, in create_tracker
    raise UnknownTracker(url)
PyBitTorrent.Exceptions.UnknownTracker: wss://tracker.openwebtorrent.com:443/announce

```

**Comment by sanderjo** [comment]
Ah, ugly ugly hack: replace `wss` with `udp` so the wss is gone:

```
cp ~/Downloads/Armbian_24.11.1_Bananapif3_noble_legacy_6.1.15.img.xz.torrent armbian.torrent
sed -i -e 's/wss:/udp:/g' armbian.torrent 
strings armbian.torrent  | grep wss # no more wss

```
... and then PyBitTorrent can handle the torrent

**Comment by gaffner** [comment]
Hey! Thank you for opening the issue and suggesting a solution. Honestly, i didnt even know web socket tracker exists, therefore i didnt address it. My guess is that they are using the same protocol as UDP/HTTP Protocol, and all it need is to change the socket type (who will be brave enough to do it...)
Anyway yeah ignore it can do the job too. Ill be happy if you can do one of them (im not in front of my laptop at the nearby time :( )

**Comment by sanderjo** [comment]
> Ill be happy if you can do one of them

Sorry, I don't understand that?

**Comment by gaffner** [comment]
Sorry for the delay, i ask if can you try to fix it? it will be appreciated 🙏
